Natural
A_natural_object_is_a_object_not_created_by_humans.
NULL

Artificial
An_artificial_object_is_an_object_created_by_humans.
NULL

Spaceship
A_spaceship_is_a_veichle_that_can_browse_the_space
Artificial
