5

Natural
A_natural_object_is_a_object_not_created_by_humans.
NULL

Artificial
An_artificial_object_is_an_object_created_by_humans.
NULL

Spaceship
A_spaceship_is_a_veichle_that_can_browse_the_space
Artificial

Planet
A_planet_is_an_astronomical_object_orbiting_a_star_or_stellar_remnant_that_is_massive_enough_to_be_rounded_by_its_own_gravity_but_isn't_massive_enough_to_cause_thermonuclear_fusion,_and_has_cleared_its_neighbouring_region_of_planetesimals.
Natural

Rogue_Planet
objects_of_planetary_mass_ejected_into_interstellar_space.
Planet

